services:
  - type: web
    name: nexusedu-backend
    env: docker
    region: singapore
    plan: free
    rootDir: backend
    dockerFilePath: Dockerfile
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: PYROGRAM_SESSION_STRING
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
